id: I849F8747
ocr_import_info:
  source: bdrc
  software: google_books
  batch: batch_2022
  expected_default_language: bo
  bdrc_scan_id: W1KG12766
  ocr_info:
    timestamp: 02/22/24T17:05:49
    html: html.zip
    txt: txt.zip
    images: images.zip
  op_import_options: {}
  op_import_version: 0.11.9
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2024-02-22 11:35:49.783471+00:00
last_modified: 2024-02-22 11:35:49.783474+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG12766
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG12766
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྩིས་ལ་འཁྲུལ་པ་སེལ་བ།
  languages:
  - bo
  author: འགོས་ལོ་ཙཱ་བ་གཞོན་ནུ་དཔལ།
statistics:
  ocr_word_mean_confidence_index: 0.9405573151419174
  ocr_word_median_confidence_index: 1.0
bases:
  I2KG207269:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2KG207269
      total_pages: 100
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2KG207269.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9405573151419174
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
